name: remote ssh command
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 10340
          script: |
            cd ~/apps/at-your-service
            git fetch origin
            git pull origin master
            git status

            cd ~/apps/at-your-service/client
            npm install
            npm run build

            cd ~/apps/at-your-service/server
            npm install
            pm2 restart 0
